///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestJenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestJenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("de9b591f-9f8d-4692-8639-7b731333931e")]
    public partial class TestJenkinsRepository : RepoGenBaseFolder
    {
        static TestJenkinsRepository instance = new TestJenkinsRepository();
        TestJenkinsRepositoryFolders.SkySuiteAppFolder _skysuite;

        /// <summary>
        /// Gets the singleton class instance representing the TestJenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("de9b591f-9f8d-4692-8639-7b731333931e")]
        public static TestJenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestJenkinsRepository() 
            : base("TestJenkinsRepository", "/", null, 0, false, "de9b591f-9f8d-4692-8639-7b731333931e", ".\\RepositoryImages\\TestJenkinsRepositoryde9b591f.rximgres")
        {
            _skysuite = new TestJenkinsRepositoryFolders.SkySuiteAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("de9b591f-9f8d-4692-8639-7b731333931e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SkySuite folder.
        /// </summary>
        [RepositoryFolder("a50d331b-a6c9-4b9a-913d-2fb292344b15")]
        public virtual TestJenkinsRepositoryFolders.SkySuiteAppFolder SkySuite
        {
            get { return _skysuite; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class TestJenkinsRepositoryFolders
    {
        /// <summary>
        /// The SkySuiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("a50d331b-a6c9-4b9a-913d-2fb292344b15")]
        public partial class SkySuiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new SkySuite  folder.
            /// </summary>
            public SkySuiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SkySuite", "/form[@processname='Sky.Suite']", parentFolder, 30000, null, true, "a50d331b-a6c9-4b9a-913d-2fb292344b15", "")
            {
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "?/?/grip[@automationid='titleThumb']/button[@automationid='PART_CloseButton']", 30000, null, "6793eac6-2e19-487b-9d6b-656da4c39e2e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a50d331b-a6c9-4b9a-913d-2fb292344b15")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a50d331b-a6c9-4b9a-913d-2fb292344b15")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("6793eac6-2e19-487b-9d6b-656da4c39e2e")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("6793eac6-2e19-487b-9d6b-656da4c39e2e")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}